# Generated by Django 2.1.4 on 2019-08-13 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('0', 'Complete Syllabus')], max_length=1)),
                ('Topic', models.CharField(max_length=50)),
                ('source', models.CharField(choices=[('0', "Self/Friend's"), ('1', "Teacher's")], max_length=1)),
                ('uploaded_by', models.CharField(max_length=50)),
                ('pdf', models.FileField(upload_to='notes/Notes/')),
            ],
            options={
                'verbose_name_plural': 'Notes',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semester', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.Semester')),
            ],
        ),
        migrations.AddField(
            model_name='notes',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.Semester'),
        ),
        migrations.AddField(
            model_name='notes',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.Subjects'),
        ),
    ]
