# Generated by Django 2.1.4 on 2019-08-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20190813_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='semester',
        ),
        migrations.AddField(
            model_name='subjects',
            name='Year',
            field=models.CharField(choices=[('First', '1st'), ('Second', '2nd'), ('Third', '3rd')], default='Third', max_length=15),
        ),
    ]
